rm grailsource/cherrypyserver/*~
rm grailsource/domsocket/*~
rm grailsource/domsocket/basic_widgets/*~
rm grailsource/domsocket/messages/*~
rm grailsource/domsocket/tester/*~
rm grailsource/scripts/*~
rm grailsource/test/*~
rm grailsource/tester/*~
rm grailsource/tester/test/*~
rm grailsource/tester/widgets/*~
rm grailsource/config/*~
rm grailsource/config/test/*~
rm grailsource/config/widgets/*~
rm *~
