rm source/cherrypyserver/*~
rm source/domsocket/*~
rm source/domsocket/basic_widgets/*~
rm source/domsocket/messages/*~
rm source/domsocket/tester/*~
rm source/scripts/*~
rm source/test/*~
rm source/tester/*~
rm source/tester/test/*~
rm source/tester/widgets/*~
rm source/config/*~
rm source/config/test/*~
rm source/config/widgets/*~
rm *~
