#!python

import os
import argparse

def build_is_safe():
    y = 'y'
    try:
        user_key = input('If you have made changes to files in this directory, they '\
                         'may become overwritten, and you should run ./build.sh instead of this script.\n'\
                         'Are you sure you wish to use the '\
                         'current directory as a destination to force copy the docker '\
                         'cherrypyserver build files and start the docker image build process? (y/N)')
    except (NameError, SyntaxError):
        user_key = 'n'
    if user_key != y:
        print('User cancelled:  Not running build or copying any files.')
        return False
    return True

def setup_build():
    import site
    site_packages = site.getsitepackages()
    for site_package_location in site_packages:
        location = os.path.join(site_package_location,
                                'domsocket', 'data', 'cherrypyserver')
        if os.path.isdir(location):
            os.system('cp -rf %s/* .' % (location,))
            os.system('chmod a+x *.sh')
            os.system('chmod a+x serve.py')
            try:
                os.system('mkdir keys')
            except OSError:
                pass
            return
    raise Exception('Could not find domsocket at any site package location')

def run_build():
    parser = argparse.ArgumentParser(description='Copy files and build cherrypyserver')
    parser.add_argument('-n', '--insecure', action='store_true',
                        help='Build the insecure version of the server (cherrypyinsecureserver)')
    args = parser.parse_args()

    if args.insecure:
        os.system('./switchtoinsecurebuild.sh')

    os.system('./build.sh')

if __name__ == '__main__':
    if build_is_safe():
        setup_build()
        run_build()
