#!python

import os

def copy_is_safe():
    y = 'y'
    try:
        user_key = input('If you have made changes to files in this directory, they '\
                         'may become overwritten, and you create a new clean directory.'\
                         'Are you sure you wish to use the '\
                         'current directory as a destination to force copy the tester '\
                         'test app? (y/N)')
    except NameError:
        print('User cancelled:  Not copying any files.')
        return False
    return True

def setup_build():
    import site
    site_packages = site.getsitepackages()
    for site_package_location in site_packages:
        location = os.path.join(site_package_location,
                                'domsocket', 'data', 'test')
        if os.path.isdir(location):
            os.system('cp -rf %s/* .' % (location,))
            os.system('chmod a+x app.py')
            os.system('chmod a+x runtests.py')
            os.system('chmod a+x coveragereport.sh')
            return
    raise Exception('Could not find domsocket/data/test at any site package location')

def run_test():
    import sys
    sys.path.append('.')
    import runtests

    summary = runtests.run()
    if summary.get_fail_count():
        print(summary)
    else:
        os.system('./coveragereport.sh')

if __name__ == '__main__':
    if copy_is_safe():
        setup_build()
        run_test()

